### ISSUE TITLE
visual studio code issue

### ISSUE THREAD

**Issue by Metzis** [coolio986/Marlin_2.0.x_Anycubic_Chiron#13]
hey i could use some help with this one. I went with vsc cause i read that is more flexible with this mode that arduino  but still got an error! i made my changes i config.h saved it and tried to build but i got this! please help!
by the way thanks coolio986 for the hard work here!
![Capture](https://user-images.githubusercontent.com/74719975/99727594-e6406780-2ac0-11eb-9309-e8e815a164b3.JPG)
![Capture1](https://user-images.githubusercontent.com/74719975/99728136-a332c400-2ac1-11eb-8cf5-fc8522781f6e.JPG)

**Comment by coolio986** [comment]
Can you post your config and config_adv?

**Comment by Metzis** [comment]
coolio986 i feel stupid right now. I was right on patching the files to send them over and i went over the code one more time! Guess what, i had the port value wrong :P change it back to 0 and everything is golden! thankS and sorry for the waste of time!
