### ISSUE TITLE
Manual Mesh Bed Level not working

### ISSUE THREAD

**Issue by data-toaster** [coolio986/Marlin_2.0.x_Anycubic_Chiron#5]
### Description

The MMBL procedure doesn't work, neither from the LCD nor from Octoprint.  

### Steps to Reproduce

1. Compile the sketch and upload. In my case, I have TMCs on all axis but the extruder, so I changed that to the original.  
2. Upload works fine, the printer is working ok.
3. Home all axis (Note: this is not mentioned in the README)
4. Start the procedure, from LCD or Octoprint 

**Expected behaviour:** Work as expected

**Actual behaviour:** The extruder moves up approx. 40 mm, but doesn't move to point n.1. Lowering or raising the extruder doesn't work. Trying from Octoprint via sending commands (G91 and subsequently G1) doesn't work as well, and the terminal continuously output `busy processing`.   

Also experienced printer reset after pressing lower or raise extruder several times.  

#### Additional Information

How to I fix this ? Since I cannot use the OEM probe, what other levelling methods are available ?

**Comment by coolio986** [comment]
I have not seen this behavior yet. I am using this firmware on my chiron. I do a flash direct from the repository then issue a G28, then a G29 and it homes a probes as expected. I am also using the oem probe. If you are using something else, then you will have to troubleshoot any electrical issues you may be having.
